enrichment_fields:
  ФИО: '[А-ЯЁ][а-яё]+\s[А-ЯЁ][а-яё]+\s[А-ЯЁ][а-яё]+'
  Дата рождения: '\b\d{2}\.\d{2}\.\d{4}\b'
  Серия паспорта: 'паспорт.*?(\d{2}\s\d{2})'
  Номер паспорта: 'паспорт.*?\d{2}\s\d{2}\s?(\d{6})'
  Кем выдан: 'выдан[^\w\d]*(.+?)(?=,|код|$)'
  Код подразделения: '\b\d{3}-\d{3}\b'
  Адрес регистрации: 'адрес регистрации: (.+)'
  ИНН: '\b\d{12}\b'
  ОГРНИП: '\b\d{15}\b'
  Телефон: '7\d{10}'
  Электронная почта должника: '[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+'
  Сумма займа: 'Сумма займа составляет (\d[\d\s]*) рублей'
  Срок займа: 'Заем выдается на (\d+) дней'
  Процентная ставка: 'Процентная ставка.*?(\d{1,2}[.,]\d{1,2})\s*%' 