input_fields:
  - №п
  - Наименование должника/ФИО
  - ИНН
  - Телефон должника
  - Электронная почта должника
  - Адрес
  - № договора займа
  - Дата выдачи займа
  - Сумма займа
  - Общая сумма задолженности
  - Задолженность по основному договору
  - Задолженность по процентам
  - Задолженность по пениям
  - Срок просроченной задолженности 